version: '3'
services:
  auth-ms:
    build: ./
    restart: on-failure
    ports:
      - 6000:3200
    depends_on:
      - auth-db
      - user-db
    environment:
      - REDIS_URL=auth-db:6379
      - USER_DB_URL=user-db:5432

  auth-db:
    image: redis:5-alpine
    ports:
      - 6001:6379
  
  user-db:
    image: postgres
    volumes:
      - /user-ms/db
    ports:
      - '5001:5432'
