version: "2.1"
services:
  app-ms:
    build: ./
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - redis-db
    environment:
      - REDIS_URL=redis://auth-db

  redis-db:
    image: redis:5-alpine
    container_name: auth-db
    ports:
      - 6379:6379
